# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: 新溪blog
subtitle: 新溪-gordon之胡写乱画
description: Just do it now.
keywords: "golang,erlang"
author: 赵卫国
language: zh-CN
timezone:


# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://blog.zhaoweiguo.com
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:
- 'CNAME'
- 'robots.txt'

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: true
  tab_replace:
  
# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date
  
archive_generator:
  per_page: 10
  yearly: true
  monthly: true
  daily: false

# Category & Tag
category_generator:
  per_page: 5
  enable_index_page: true

tag_generator:
  per_page: 5
  enable_index_page: true

default_category: default
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
##theme: landscape
theme: newnext

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: git
  repo: git@github.com:zhaoweiguo/zhaoweiguo.github.io.git
  branch: master
  message: "Updated: {{ now('YYYY-MM-DD HH:mm:ss') }}"



# added on 20181204


server:
  port: 4000

marked:
  # For preserve original quotes in code blocks.
  smartypants: false
  # For disable links in code blocks.
  autolink: false

kramed:
  # For preserve original quotes in code blocks.
  smartypants: false

search:
  path: search.xml
  field: post,tag

symbols_count_time:
  symbols: true
  time: true
  total_symbols: true
  total_time: true


# ===============================================================
# NexT Configuration
# ===============================================================

theme_config:

# ---------------------------------------------------------------
# Theme Core Configuration Settings
# ---------------------------------------------------------------
  cache:
    enable: true

  custom_file_path:
    styles: source/_data/styles.styl

# ---------------------------------------------------------------
# Site Information Settings
# ---------------------------------------------------------------
  footer:
    since: 2018
    icon:
      name: heart
      animated: true
      color: "#808080"
    copyright: zhaoweiguo
    powered:
      enable: true
      version: true
    theme:
      enable: true
      version: true
    beian:
      enable: true
      icp: 京ICP备16018553号

  creative_commons:
    license: by-nc-sa
    sidebar: true
    post: true

# ---------------------------------------------------------------
# SEO Settings
# ---------------------------------------------------------------
  seo: true
  index_with_subtitle: true
  exturl: true


# ---------------------------------------------------------------
# Menu Settings
# ---------------------------------------------------------------

  menu:
    home: / || bullhorn
    archives: /archives/ || archive
    categories: /categories/ || th
    tags: /tags/ || tags
    #about: /about || about
    #schedule: /schedule/ || calendar
    #sitemap: /sitemap.xml || sitemap
    #commonweal: /404/ || heartbeat

  menu_settings:
    icons: true
    badges: true


# ---------------------------------------------------------------
# Scheme Settings
# ---------------------------------------------------------------
  #scheme: Muse
  #scheme: Mist
  #scheme: Pisces
  scheme: Gemini

# ---------------------------------------------------------------
# Sidebar Settings
# ---------------------------------------------------------------
  favicon:
    small: /images/icon.png

  avatar:
    url: /images/icon.png
    rounded: true
    opacity: 1
    rotated: true

  social:
    GitHub: https://github.com/zhaoweiguo || github
    E-Mail: mailto:support@zhaoweiguo.com || envelope

    # Gitter: https://gitter.im/theme-next || github-alt
    # Riot: https://riot.im/app/#/room/#NexT:matrix.org || bullhorn

    # Telegram [Chat]: https://t.me/joinchat/GUNHXA-vZkgSMuimL1VmMw || telegram
    # Telegram [News]: https://t.me/theme_next || telegram

  social_icons:
    enable: true
    icons_only: true
    transition: true

  github_banner: https://github.com/zhaoweiguo/zhaoweiguo.github.io || Fork me on GitHub

  toc:
    enable: true
    number: true
    wrap: true

  sidebar:
    position: left
    width: 300
    b2t: true   # Back to top button
    scrollpercent: true # display scroll percent label in Back to top button
    onmobile: true
    display: post
    #display: always
    #display: hide
    #display: remove


# ---------------------------------------------------------------
# Post Settings
# ---------------------------------------------------------------
  post_edit:
    enable: false
    url: https://github.com/theme-next/theme-next.org/edit/source/source/_posts/

  post_meta:
    item_text: true
    created_at: true
    updated_at:
      enabled: true
    categories: true

  symbols_count_time:
    separated_meta: true
    item_text_post: true
    item_text_total: true
    symbols: true
    time: true
    total_symbols: true
    total_time: true
  codeblock:
    border_radius:
  # highlight_theme: normal
  # highlight_theme: night
  highlighdt_theme: night blue
  # highlight_theme: night bright
  # highlight_theme: night eighties

  auto_excerpt: # 截断相关
    enable: true
    length: 350


# ---------------------------------------------------------------
# Misc Theme Settings
# ---------------------------------------------------------------
  mobile_layout_economy: true

# ---------------------------------------------------------------
# Third Party Services Settings
# ---------------------------------------------------------------
  math:
    enable: true
    per_page: true
    engine: mathjax
    mathjax:
      cdn: //cdn.jsdelivr.net/npm/mathjax@2.7.1/MathJax.js?config=TeX-AMS-MML_HTMLorMML

# local search
  local_search:
    enable: false
    trigger: auto
    top_n_per_article: 1

# ---------------------------------------------------------------
# Comment Settings  注: 其他comment插件详见theme
# ---------------------------------------------------------------

# Disqus
  disqus:
    enable: false
    shortname: zhaoweiguo
    count: true
    lazyload: true


# Gitalk 
# Demo: https://gitalk.github.io
# Reference: https://asdfv1929.github.io/2018/01/20/gitalk/, https://liujunzhou.cn/2018/8/10/gitalk-error/#more,  https://iochen.com/post/use-gitalk-in-hexo/
  gitalk:
    enable: true
    ClientID: 74ff30da6cc8deafe946
    ClientSecret: 65ff50b923a60ef39f312c2014035b6285eff2d5
    owner: zhaoweiguo
    repo: zhaoweiguo.github.io
    adminUser: "['zhaoweiguo']"
    id: location.pathname   #id: md5(location.pathname),   # https://github.com/gitalk/gitalk/issues/115
    labels: "['Gitalk']"
    perPage: 15
    pagerDirection: last
    createIssueManually: false
    distractionFreeMode: true  # Facebook-like distraction free mode



# ---------------------------------------------------------------
# Tags Settings
# ---------------------------------------------------------------
  note:
    style: simple
    icons: true
    border_radius: 0
    light_bg_offset: -3

  tabs:
    enable: true
    transition:
      tabs: true
      labels: true
    border_radius: 0

  motion:
    enable: false
    async: true
    transition:
      post_block: fadeIn
      post_header: slideDownIn
      post_body: slideDownIn
      coll_header: slideLeftIn
      # Only for Pisces | Gemini.
      sidebar: slideUpIn

  lazyload: true

# ---------------------------------------------------------------
# Advance Settings
# ---------------------------------------------------------------

  # rss:


